homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('Hobi/', views.hobi, name='hobi'),
    path('Pengalaman/', views.pengalaman, name='pengalaman'),
    path('Contact/', views.contact, name='contact'),
    path('Pelajaran/', views.pelajaran, name='pelajaran')
]

myform/urls.py
from django.urls import path
from .views import Join, sched_delete

app_name = 'myform'

urlpatterns = [
    path('', Join, name="Pelajaran"),
    path('<int:pk>', sched_delete, name="Delete")
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include;

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Pelajaran/', include('myform.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.

myform/models.py
from django.db import models

# Create your models here.
class Pelajaran(models.Model):
    NamaMatkul = models.CharField(max_length = 50, default="")
    DosenPengajar = models.CharField(max_length = 50, default="")
    JumlahSKS = models.CharField(max_length=50, default="")
    DeskripsiMataKuliah = models.CharField(max_length = 100, default="")
    SemesterTahun = models.CharField(max_length = 50, default="")
    RuangKelas = models.CharField(max_length=50, default="")
    

myform/forms.py
from django import forms

class PelForm(forms.Form):
    NamaMatkul = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))

    DosenPengajar = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen Pengajar',
        'type' : 'text',
        'required' : True,
    }))

    JumlahSKS = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True,
    }))

    DeskripsiMataKuliah= forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))

    SemesterTahun = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Gasal/Genap 2019/2020',
        'type' : 'text',
        'required' : True,
    }))

    RuangKelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Ruang Kelas',
        'type' : 'text',
        'required' : True,
    }))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'Profile.html')

def pengalaman(request):
    return render(request, 'Pengalaman.html')

def hobi(request):
    return render(request, 'Hobi.html')

def contact(request):
    return render(request, 'Contact.html')

def pelajaran(request):
    return render(request, 'Pelajaran.html')

myform/views.py
from django.shortcuts import render, redirect
from .models import Pelajaran as jadwal
from .forms import PelForm

# Create your views here.

def Join(request):
    if request.method == 'POST':
        form = PelForm(request.POST)
        if form.is_valid():
            sched = jadwal()
            sched.NamaMatkul = form.cleaned_data['NamaMatkul']
            sched.DosenPengajar = form.cleaned_data['DosenPengajar']
            sched.JumlahSKS = form.cleaned_data['JumlahSKS']
            sched.DeskripsiMataKuliah = form.cleaned_data['DeskripsiMataKuliah']
            sched.SemesterTahun = form.cleaned_data['SemesterTahun']
            sched.RuangKelas = form.cleaned_data['RuangKelas']
            sched.save()
        return redirect('/Pelajaran')
    else:
        sched = jadwal.objects.all()
        form = PelForm()
        response = {'sched':sched, 'form':form}
        return render(request, 'Pelajaran.html', response)

def sched_delete(request, pk):
    if request.method == 'POST':
        form = PelForm(request.POST)
        if form.is_valid():
            sched = jadwal()
            sched.NamaMatkul = form.cleaned_data['NamaMatkul']
            sched.DosenPengajar = form.cleaned_data['DosenPengajar']
            sched.JumlahSKS = form.cleaned_data['JumlahSKS']
            sched.DeskripsiMataKuliah = form.cleaned_data['DeskripsiMataKuliah']
            sched.SemesterTahun = form.cleaned_data['SemesterTahun']
            sched.RuangKelas = form.cleaned_data['RuangKelas']
            sched.save()
        return redirect('/Pelajaran')
    else:
        jadwal.objects.filter(pk=pk),delete()
        data = jadwal.objects.all()
        form = PelForm()
        response = {'sched':data, 'form':form}
        return render(request, 'Pelajaran.html', response)

homepage/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kontak saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Kontak Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pelajaran' %}">Jadwal</span></a>
            </li>
          </ul>
        </div>
      </nav>
    

    <div class="section4">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <p></p>
                    <br>
                    <h1 class="font-profle" style="color: red;">Social Media</h1>
                </div>
            </div>
            <div class="row" style="margin-left: 7.5em;margin-bottom: 30em">
                <div class="col-md-4">
                    <a href="https://api.whatsapp.com/send?phone=6281212025741">                                        
                        <img class="rounded-circle hover" src="{% static 'whatsapp.png' %}" style="width: 50%;">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="https://www.instagram.com/alfred_prasetio/?hl=id">                                        
                        <img class="rounded-circle hover" src="{% static 'instagram.png' %}" style="width: 50%;">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="https://line.me/R/ti/p/alfred_prasetio">                                        
                        <img class="rounded-circle hover" src="{% static 'line.png' %}" style="width: 50%;">
                    </a>
                </div>
            </div>
        </div>        
    </div>

</body>
</html>

homepage/templates/Hobi.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobi saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Hobi Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link " href="{% url 'homepage:hobi' %}">Hobi<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:pelajaran' %}">Jadwal</a>
          </li>
          </ul>
        </div>
      </nav>
    
    <div class="section2">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h1 class="font-profile">Gaming</h1>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 50%; height: 50%; margin: auto;">
                         <div class="carousel-item active">
                           <img class="d-block w-100" src="{% static 'valorant.jpg' %}". alt="First slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>Valorant</h5>
                          </div>
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'dota.jpg' %}" alt="Second slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>DoTA 2</h5>
                          </div>                          
                        </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'genshin.png' %}" alt="Third slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5 style="color: black;">Genshin Impact</h5>
                          </div>                          
                        </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'among.jpg' %}" alt="Fourth slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>Among Us</h5>
                          </div>                          
                        </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                         <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href='#carouselExampleControls' role="button" data-slide="next">
                         <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                        <p></p>
                </div>
            </div>
        </div>
        <div class="container">
          <div class="row">
              <div class="col-md-12" style="text-align: center;">
                  <h1 class="font-profile">Gaming adalah hobi saya sejak SMP. Saya mulai bermain game karena diajak oleh teman saya. Saya tertarik dengan game dan akhirnya saya hobi bermain game.</h1>
                  <p></p>
              </div>
          </div>
      </div>
    </div>

</body>
</html>

homepage/templates/Pelajaran.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jadwal Pelajaran</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Jadwal Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:pelajaran' %}">Jadwal<span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action='' method='POST'>
                    {% csrf_token %}
                    {{ form }}
                    <div class="centre-items">
                        <input type="submit" class="btn btn-primary" value="Tambah Matkul">
                    </div>
                </form>
                <table class ="table">
                    <thead>
                        <tr>
                            <th scope ="col">Nama Mata Kuliah</th>
                            <th scope ="col">Dosen Pengajar</th>
                            <th scope ="col">Jumlah SKS</th>
                            <th scope ="col">Deskripsi Mata Kuliah</th>
                            <th scope ="col">Semester Tahun</th>
                            <th scope ="col">Ruang Kelas</th>
                            <th scope ="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for jadwal in sched %}
                            <tr>
                                <th scope ="row">{{jadwal.NamaMatkul}}</th>
                                <td>{{jadwal.DosenPengajar}}</td>
                                <td>{{jadwal.JumlahSKS}}</td>
                                <td>{{jadwal.DeskripsiMataKuliah}}</td>
                                <td>{{jadwal.SemesterTahun}}</td>
                                <td>{{jadwal.RuangKelas}}</td>
                                <td><a href="{% url 'Delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger">Delete</button></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</head>
</html>

homepage/templates/Pengalaman.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pengalaman saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Pengalaman Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:pelajaran' %}">Jadwal</a>
          </li>
          </ul>
        </div>
      </nav>
    
      <div class="section3">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h1 class="font-profile" style="color: black;">Fotografi</h1>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 50%; height: 50%; margin: auto;">
                         <div class="carousel-item active">
                           <img class="d-block w-100" src="{% static 'img1.JPG' %}" alt="First slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img2.JPG' %}" alt="Second slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img3.JPG' %}" alt="Third slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img4.JPG' %}" alt="Fourth slide">
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                         <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                         <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                        <p></p>
                </div>
            </div>
        </div>
        
        </div>
    </div>
</body>
</html>